# Base configs
baseurl: "annagreenelaf.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Anna Greenleaf Photography"
subtitle: ""
author: "Anna Greenleaf"
bio: "I am a teen photographer based out of New York City. Although I mainly focus on portrait photography, I enjoy taking various types of photos. Please feel free to contact me regarding any questions."
publicise: ""
web_design: "Isabella"
social_urls:
  instagram: "https://www.instagram.com/anna.greenleaf"
  